# Generated by Django 3.2.9 on 2022-03-31 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTreeLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSetLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCardLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VariableLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VariablePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=40)),
                ('datatype', models.CharField(choices=[('b', 'Bool'), ('F', 'Float'), ('I', 'Integer')], default='b', help_text='Data Type', max_length=1)),
                ('fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.variablelibrary')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCardPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(help_text='Rule', null=True)),
                ('weight', models.FloatField(default='1', help_text='Weight')),
                ('score', models.FloatField(default='1', help_text='Score')),
                ('fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.scorecardlibrary')),
            ],
        ),
        migrations.CreateModel(
            name='RuleSetPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(help_text='Rule', null=True)),
                ('action', models.TextField(blank=True, help_text='Action', null=True)),
                ('naction', models.TextField(blank=True, help_text='nAction', null=True)),
                ('fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.rulesetlibrary')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionTreePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(help_text='Rule', null=True)),
                ('log', models.TextField(blank=True, help_text='Log')),
                ('fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.decisiontreelibrary')),
                ('prev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.decisiontreepool')),
            ],
        ),
    ]
