# Generated by Django 3.2.9 on 2021-12-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_scorecardpool_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecardpool',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='scorecardpool',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='scorecardpool',
            name='value',
        ),
        migrations.AddField(
            model_name='scorecardpool',
            name='rule',
            field=models.TextField(help_text='Rule', null=True),
        ),
    ]
