# Generated by Django 3.2.9 on 2021-12-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20211201_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variablepool',
            old_name='collection',
            new_name='datatype',
        ),
    ]
