# Generated by Django 3.2.9 on 2021-12-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_decisiontreelibrary_decisiontreepool'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisiontreepool',
            name='log',
            field=models.TextField(blank=True, help_text='Log'),
        ),
    ]
