# Generated by Django 3.2.9 on 2021-12-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_decisiontreepool_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontreepool',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.decisiontreepool'),
        ),
    ]
