# Generated by Django 3.2.11 on 2022-01-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_decisiontreepool_prev'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablepool',
            name='intvalue',
            field=models.IntegerField(default=5),
        ),
    ]
