# Generated by Django 3.2.9 on 2022-01-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_variablepool_intvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablepool',
            name='intvalue',
        ),
    ]
