# Generated by Django 3.2.9 on 2022-01-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_remove_variablepool_intvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablepool',
            name='datatype',
            field=models.CharField(choices=[('b', 'Bool'), ('F', 'Float'), ('I', 'Integer')], default='b', help_text='Data Type', max_length=1),
        ),
        migrations.AlterField(
            model_name='variablepool',
            name='name',
            field=models.CharField(help_text='Enter name', max_length=40),
        ),
    ]
