# Generated by Django 3.2.11 on 2022-01-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_remove_variablepool_intvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablepool',
            name='name',
            field=models.CharField(help_text='Enter name', max_length=40),
        ),
    ]
