# Generated by Django 3.2.9 on 2022-01-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_remove_variablepool_intvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=100)),
                ('name', models.CharField(max_length=100)),
                ('income', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='variablepool',
            name='name',
            field=models.CharField(help_text='Enter name', max_length=40),
        ),
    ]
