# Generated by Django 3.2.9 on 2022-01-30 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20220127_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSetLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSetPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(help_text='Rule', null=True)),
                ('action', models.TextField(help_text='Action', null=True)),
                ('fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.rulesetlibrary')),
            ],
        ),
    ]
