# Generated by Django 3.2.9 on 2022-01-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_rename_completed_system_status'),
        ('system', '0011_auto_20220120_1619'),
    ]

    operations = [
    ]
