# Generated by Django 3.2.9 on 2022-01-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_merge_20220120_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='System',
        ),
    ]
