# Generated by Django 3.2.9 on 2022-01-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_auto_20220127_2003'),
        ('system', '0013_delete_system'),
    ]

    operations = [
    ]
