# Generated by Django 3.2.9 on 2022-01-31 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20220131_1455'),
        ('system', '0014_merge_0011_auto_20220127_2003_0013_delete_system'),
    ]

    operations = [
    ]
