# Generated by Django 3.2.9 on 2022-03-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_merge_20220131_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
