# Generated by Django 3.2.9 on 2022-03-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_variablepool_name'),
        ('system', '0015_merge_20220131_1914'),
    ]

    operations = [
    ]
