# Generated by Django 3.2.9 on 2022-03-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_merge_20220321_0238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
