# Generated by Django 3.2.9 on 2022-03-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_delete_user'),
        ('system', '0017_delete_user'),
    ]

    operations = [
    ]
