@host = http://127.0.0.1:8000

GET {{host}}/RuleSetEngine/
Content-Type: application/json

{
    "fk":4,
    "circular":false,
    "varmap":{
        "28": true,
        "29": true,
        "30": 240000,
        "31": 20,
        "32": true
    }
}

###

GET {{host}}/ScoreCardEngine/
Content-Type: application/json

{
    "fk":2,
    "varmap":{
        "1": 1,"2":1.5,"3":50
    }
}

###

GET {{host}}/DecisionTreeEngine/
Content-Type: application/json

{
    "fk":1,
    "varmap":{"1": 1, "3": 65}
}

###